name: Update Last Run Badge

on:
  workflow_run:
    workflows: ["Daily E2E Test Report"]
    types:
      - completed

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate badge JSON
      run: |
        mkdir -p .github/badge
        echo '{
          "schemaVersion": 1,
          "label": "Last E2E Run",
          "message": "'$(date -u +%Y-%m-%d)'",
          "color": "green"
        }' > .github/badge/badge.json

    - name: Commit and push badge
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .github/badge/badge.json
        git commit -m "Update badge" || echo "No changes"
        git push

